export const FETCH_INVOICE_LIST = "FETCH_INVOICE_LIST";
export const FETCH_INVOICE_FAIL = "FETCH_INVOICE_FAIL";

export const GET_DATEPICKER = "GET_DATEPICKER";
export const GET_KEYWORD = "GET_KEYWORD";

export const FETCH_SUMMARY_INVOICE_LIST = "FETCH_SUMMARY_INVOICE_LIST";
export const FETCH_SUMMARY_INVOICE_LIST_FAIL = "FETCH_SUMMARY_INVOICE_LIST_FAIL";
