export const FETCH_INVOICE_LIST = "FETCH_INVOICE_LIST";
export const FETCH_INVOICE_FAIL = "FETCH_INVOICE_FAIL";

export const GET_DATEPICKER = "GET_DATEPICKER";
export const GET_KEYWORD = "GET_KEYWORD";

export const FETCH_SUMMARY_INVOICE_LIST = "FETCH_SUMMARY_INVOICE_LIST";
export const FETCH_SUMMARY_INVOICE_LIST_FAIL = "FETCH_SUMMARY_INVOICE_LIST_FAIL";

export const GET_DATE_RANGE = "GET_DATE_RANGE";
export const GET_VIEW_TYPE = "GET_VIEW_TYPE";

export const FETCH_INVOICE_ITEM_SUCCESS = "FETCH_INVOICE_ITEM_SUCCESS";

export const SET_CHARGE = "SET_CHARGE";
export const SET_ISSUE_INVOICE = "SET_ISSUE_INVOICE";