export const FETCH_ITEM_LIST = 'FETCH_ITEM_LIST';
export const FETCH_ITEM_LIST_SUCCESS = 'FETCH_ITEM_LIST_SUCCESS';

export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const EDIT_ITEM = 'EDIT_ITEM';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';

export const SHOW_ITEM_FORM = "SHOW_ITEM_FORM";
export const HIDE_ITEM_FORM = "HIDE_ITEM_FORM";

export const SHOW_ADD_ITEM_BUTTON = "SHOW_ADD_ITEM_BUTTON";



