export const FETCH_ROOM_LIST = 'FETCH_ROOM_LIST';
export const FETCH_ROOM_LIST_SUCCESS = 'FETCH_ROOM_LIST_SUCCESS';
export const FETCH_ROOM_LIST_FAIL = 'FETCH_ROOM_LIST_FAIL';

export const FILTER_ROOM_TYPE = 'FILTER_ROOM_TYPE';
export const FILTER_ROOM_TYPE_SUCCESS = 'FILTER_ROOM_TYPE_SUCCESS';

export const BOOK = 'CHECKIN';
export const BOOK_FAIL = 'CHECKIN_FAIL';

export const FETCH_ROOM_BY_ID_SUCCESS = 'FETCH_ROOM_BY_ID_SUCCESS';

export const SET_SURCHARGE = 'SET_SURCHARGE';


