export const FETCH_ROOM_LIST = 'FETCH_ROOM_LIST';
export const FETCH_ROOM_LIST_SUCCESS = 'FETCH_ROOM_LIST_SUCCESS';
export const FETCH_ROOM_LIST_FAIL = 'FETCH_ROOM_LIST_FAIL';

export const FILTER_ROOM_TYPE = 'FILTER_ROOM_TYPE';
export const FILTER_ROOM_TYPE_SUCCESS = 'FILTER_ROOM_TYPE_SUCCESS';


